CREATE TABLE restaurant (
    restaurant_id INT AUTO_INCREMENT PRIMARY KEY,
    restaurant_name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    holiday VARCHAR(100),
    waiting_time INT,
    opening_hours VARCHAR(100),
    break_time VARCHAR(100),
    reservation_method VARCHAR(100),
    recommended_menu VARCHAR(255),
    average_price VARCHAR(20),
    parking_availability TINYINT(1),
    partnership_status TINYINT(1),
    solo_or_group VARCHAR(50),
    event_status TINYINT(1),
    contact_number VARCHAR(20),
    restaurant_image VARCHAR(255),
    address VARCHAR(255),
    rating DECIMAL(2,1),
    reviews INT 
